package interfaz.subventanas.ayuda;

import interfaz.subventanas.Base;
import diccionario.TPReservada;
import interfaz.Interfaz;

public class Asignacion extends Base{
    public Asignacion(Interfaz interfaz) {
        super(new Object[]{"igualar","valor","sentencia","asignacion","variable","variables","string","texto","booleano","boolean","double","doble","decimal","char","caracter","entero","int","datos","operadores","logico","logica","and","y","or","o","verdadero","falso","true","false","equivale","equals","igual","diferente","different","menorque","menoroigualque","mayorque","mayoroigualque"}, 
        "<div class=\"titulo\" style=\"padding-left:84px;\">Asignación de valores</div><br/><div style=\"padding-left:16px;\">&#09;El tipo de dato que recibe una variable dependerá de cómo se declaró la misma, existen cinco tipos de variables posibles en RBasic, estas son:</div><br/><div class=\"subTitulo\" style=\"padding-left:16px;\">ENTERO</div><br/><div style=\"padding-left:16px;\">&#09;Esta variable recibe una operación matemática o un valor numérico y esta lo expresa como un entero que podría ser -5,-3,-2,0,2,4,6 o cualquier otro, por ejemplo:</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">"
        .concat(TPReservada.R.toString())
        .concat("</span> A <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.ENTERO.toString())
        .concat("</span></div><div class=\"codigo2\">A = <span class=\"numero\">23</span></div><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> B <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.ENTERO.toString())
        .concat("</span></div><div class=\"codigo2\">B = A + <span class=\"numero\">23</span></div></div><br/><div style=\"padding-left:16px;\">&#09;Esta variable puede recibir valores enteros o decimales que veremos a continuación, pero siempre los redondeara para abajo.</div><br/><div class=\"subTitulo\"style=\"padding-left:16px;\">DECIMAL</div><br/><div style=\"padding-left:16px;\">&#09;Esta variable funciona igual que los enteros pero nos sirven para operación que tienen punto decimal, por ejemplo:</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> ESTATURA <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.DECIMAL.toString())
        .concat("</span></div><div class=\"codigo2\">ESTATURA = <span class=\"numero\">1.5</span></div><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> A <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.ENTERO.toString())
        .concat("</span></div><div class=\"codigo2\">A = <span class=\"numero\">1</span></div><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> B <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.DECIMAL.toString())
        .concat("</span></div><div class=\"codigo2\">B = A / <span class=\"numero\">2</span></div></div><br/><div class=\"subTitulo\" style=\"padding-left:16px;\">CARACTER</div><br/><div style=\"padding-left:16px;\">&#09;Este tipo de variable recibe un único carácter como valor, este puede ser tanto un 	valor literal como una variable previamente asignada, por ejemplo:</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> LETRA <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.CARACTER.toString())
        .concat("</span></div><div class=\"codigo2\">LETRA = <span class=\"cadena\">'A'</span></div></div><br/><br/><div class=\"subTitulo\" style=\"padding-left:16px;\">TEXTO</div><br/><div style=\"padding-left:16px;\">&#09;Una variable del tipo TEXTO recibe ya sea varias letras de forma literal o el valor de distintas variables para formar un texto, por ejemplo:</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> PALABRA <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.TEXTO.toString())
        .concat("</span></div><div class=\"codigo2\">PALABRA = <span class=\"cadena\">\"HOLA\"</span></div><div class=\"codigo1\">PALABRA = <span class=\"cadena\">\"JUANELO\"</span> + <span class=\"cadena\">' '</span> + <span class=\"cadena\">\"ES UN NOMBRE\"</span></div></div><br/><div style=\"padding-left:16px;\">&#09;Puede notar que puedes unir diferentes texto mediante el símbolo de (+), esto también puede ser utilizado para unir diferentes tipos de variables y tratarlas como texto.</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> PALABRAS <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.TEXTO.toString())
        .concat("</span></div><div class=\"codigo2\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> MANZANAS <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.ENTERO.toString())
        .concat("</span></div><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> NOMBRE <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.TEXTO.toString())
        .concat("</span></div><div class=\"codigo2\">NOMBRE = <span class=\"cadena\">\"PEDRO\"</span></div><div class=\"codigo1\">MANZANAS = <span class=\"numero\">2</span></div><div class=\"codigo2\">PALABRAS = NOMBRE + <span class=\"cadena\">\"TIENE\"</span> + MANZANAS + <span class=\"cadena\">\"MANZANAS\"</span></div><div class=\"codigo1\"><span class=\"funcion\">")
        .concat(TPReservada.IMPRIME.toString())
        .concat(" </span> PALABRAS</div></div><br/><div class=\"subTitulo\" style=\"padding-left:16px;\">BOOLEANO</div><br/><div style=\"padding-left:16px;\">&#09;Estas variables nos servirán para evaluar si una expresión es correcta o no, por ejemplo ¿Hace calor? La respuesta seria si o no, de igual forma funcionan las variables booleanas, se puede decir literalmente un valor como:</div><br/><div class=\"seudoCodigo\" style=\"padding-left:138px;\">[")
        .concat(TPReservada.VERDADERO.toString())
        .concat("|")
        .concat(TPReservada.FALSO.toString())
        .concat("]</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> A <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.BOOLEANO.toString())
        .concat("</span></div><div class=\"codigo2\">A = <span class=\"booleano\">VERDADERO</span></div><div class=\"codigo1\">A = <span class=\"booleano\">FALSO</span></div></div><br/><div style=\"padding-left:16px;\">&#09;O como varias expresiones con ayuda de operadores logicos, por ejemplo: </div><br/><div class=\"seudoCodigo\" style=\"padding-left:193px;\">[")
        .concat(TPReservada.Y.toString())
        .concat("|")
        .concat(TPReservada.O.toString())
        .concat("]</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> a <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.BOOLEANO.toString())
        .concat("</span></div><div class=\"codigo2\">A = <span class=\"booleano\">")
        .concat(TPReservada.VERDADERO.toString())
        .concat("</span><span class=\"palabra\"> ")
        .concat(TPReservada.O.toString())
        .concat(" </span><span class=\"booleano\">")
        .concat(TPReservada.FALSO.toString())
        .concat("</span><span class=\"palabra\"> ")
        .concat(TPReservada.Y.toString())
        .concat(" </span><span class=\"booleano\">")
        .concat(TPReservada.VERDADERO.toString())
        .concat("</span><span class=\"palabra\"> ")
        .concat(TPReservada.O.toString())
        .concat(" </span><span class=\"booleano\">")
        .concat(TPReservada.FALSO.toString())
        .concat("</span></div></div><br/><div style=\"padding-left:16px;\">&#09;Esto se rige con las tablas de verdad de los operadores AND para Y y OR para O, también es posible evaluar distintas variables para ver si cumplen con una expresión, todas las variables pueden ser evaluadas con los siguientes operadores:</div><br/><div class=\"seudoCodigo\" style=\"padding-left:137px;\">[")
        .concat(TPReservada.EQUIVALE.toString())
        .concat("|")
        .concat(TPReservada.DIFERENTE.toString())
        .concat("]</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> TEXTO1 <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.TEXTO.toString())
        .concat("</span></div><div class=\"codigo2\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> TEXTO2 <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.TEXTO.toString())
        .concat("</span></div><div class=\"codigo1\">TEXTO1 = <span class=\"cadena\">\"TEXTO\"</span></div><div class=\"codigo2\">TEXTO2 = <span class=\"cadena\">\"TEXTO\"</span></div><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> CONDICION <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.BOOLEANO.toString())
        .concat("</span></div><div class=\"codigo2\">CONDICION = TEXTO1 <span class=\"palabra\">")
        .concat(TPReservada.EQUIVALE.toString())
        .concat("</span> TEXTO2</div><div class=\"codigo1\">CONDICION = TEXTO1 <span class=\"palabra\">")
        .concat(TPReservada.DIFERENTE.toString())
        .concat("</span> TEXTO2</div></div><br/><div style=\"padding-left:16px;\">&#09;Para valores numéricos, existen otros operadores lo cuales son: </div><br/><div class=\"seudoCodigo\" style=\"padding-left:39px;font-size: 13px;\">[")
        .concat(TPReservada.MENORQUE.toString())
        .concat("|")
        .concat(TPReservada.MENOROIGUALQUE.toString())
        .concat("|")
        .concat(TPReservada.MAYORQUE.toString())
        .concat("|")
        .concat(TPReservada.MAYOROIGUALQUE.toString())
        .concat("]</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> A <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.ENTERO.toString())
        .concat("</span></div><div class=\"codigo2\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> B <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.ENTERO.toString())
        .concat("</span></div><div class=\"codigo1\">A = <span class=\"numero\">2</span></div><div class=\"codigo2\">B = <span class=\"numero\">2</span></div><div class=\"codigo1\"><span class=\"palabra\">")
        .concat(TPReservada.R.toString())
        .concat("</span> CONDICION <span class=\"palabra\">")
        .concat(TPReservada.ES.toString())
        .concat("</span> <span class=\"dato\">")
        .concat(TPReservada.BOOLEANO.toString())
        .concat("</span></div><div class=\"codigo2\">CONDICION = A <span class=\"palabra\">")
        .concat(TPReservada.MENORQUE.toString())
        .concat("</span> B </div></div><br/><br/><br/>"), "Asignacion de valor a variables", interfaz);
    }
}