package interfaz.subventanas.ayuda;

import interfaz.subventanas.Base;
import diccionario.TPReservada;
import interfaz.Interfaz;

public class Ciclos extends Base{
    public Ciclos(Interfaz interfaz) {
        super(new Object[]{"ciclo","loop","for","while","de","mientras"}, 
                "<div class=\"titulo\"style=\"padding-left:188px;\">Ciclos</div>"
                .concat("<br/><div class=\"subTitulo\"style=\"padding-left:25px;\">Ciclo DE</div><br/><div style=\"padding-left:25px;\">&#09;El ciclo de pasos nos permite repetir una o varias operaciones, una cierta cantidad de veces, la estructura del ciclo es la siguiente:</div><br/><div class=\"seudoCodigo\"style=\"padding-left:25px;font-size:11px;\"><div>[")
                .concat(TPReservada.DE.toString())
                .concat("] {<span style=\"font-style:italic;\">variable</span>} [=] {<span style=\"font-style:italic;\">valor</span>} [")
                .concat(TPReservada.HASTA.toString())
                .concat("] {<span style=\"font-style:italic;\">valor que llegara la variable</span>} [")
                .concat(TPReservada.PASO.toString())
                .concat("] {<span style=\"font-style:italic;\">operación</span>} [")
                .concat(TPReservada.ENTONCES.toString())
                .concat("]</div><div></div><div>[")
                .concat(TPReservada.TDE.toString())
                .concat("]</div></div><br/><div style=\"padding-left:25px;\">&#09;A los valores del ciclo se le pueden asignar con respeto de una variable previamente asignada aunque también puedes asignarle un valor literalmente, por ejemplo:</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">")
                .concat(TPReservada.R.toString())
                .concat("</span> INICIO <span class=\"palabra\">")
                .concat(TPReservada.ES.toString())
                .concat("</span> <span class=\"dato\">")
                .concat(TPReservada.ENTERO.toString())
                .concat("</span></div><div class=\"codigo2\">INICIO = <span class=\"numero\">0</span></div><div class=\"codigo1\"><span class=\"palabra\">")
                .concat(TPReservada.DE.toString())
                .concat("</span> I = INICIO <span class=\"palabra\">")
                .concat(TPReservada.HASTA.toString())
                .concat("</span> <span class=\"numero\">5</span> <span class=\"palabra\">")
                .concat(TPReservada.PASO.toString())
                .concat("</span> I + <span class=\"numero\">1</span> <span class=\"palabra\">")
                .concat(TPReservada.ENTONCES.toString())
                .concat("</span></div><div class=\"codigo2\">&#09;<span class=\"funcion\">")
                .concat(TPReservada.IMPRIME.toString())
                .concat("</span> <span class=\"cadena\">\"I: \"</span> + I</div><div class=\"codigo1\"><span class=\"palabra\">")
                .concat(TPReservada.TDE.toString())
                .concat("</span></div></div><br/><div style=\"padding-left:25px;\">&#09;Pero ten cuidado que si no piensas bien como hacer tu ciclo puedes llegar a hacer un ciclo infinito en el mismo.</div><br/><div class=\"subTitulo\" style=\"padding-left:25px;\">Ciclo MIENTRAS</div><br/><div style=\"padding-left:25px;\">&#09;Esta operación recibe una condición booleana o una declaración literal y va a ejecutar el bloque de código que tenga ingresado. Revisa primero la condición y en caso de ser verdadera la afirmación, entonces procederá a la ejecución.</div><br/><div class=\"seudoCodigo\" style=\"padding-left:25px;\"><div>[")
                .concat(TPReservada.MIENTRAS.toString())
                .concat("] {<span style=\"font-style:italic;\">Condición</span>} [")
                .concat(TPReservada.ENTONCES.toString())
                .concat("]</div><div></div><div>[")
                .concat(TPReservada.TMIENTRAS.toString())
                .concat("]</div></div><br/><div style=\"padding-left:25px;\">&#09;Como en cualquier otro lenguaje de programación un error lógico puede desencadenar un bucle en el sistema. Ejemplo:</div><br/><div class=\"caja\"><div class=\"codigo1\"><span class=\"palabra\">")
                .concat(TPReservada.R.toString())
                .concat("</span> INDEX <span class=\"palabra\">")
                .concat(TPReservada.ES.toString())
                .concat("</span> <span class=\"dato\">")
                .concat(TPReservada.ENTERO.toString())
                .concat("</span></div><div class=\"codigo2\">INDEX = <span class=\"numero\">0</span></div><div class=\"codigo1\"><span class=\"palabra\">")
                .concat(TPReservada.R.toString())
                .concat("</span> BANDERA <span class=\"palabra\">")
                .concat(TPReservada.ES.toString())
                .concat("</span> <span class=\"dato\">")
                .concat(TPReservada.BOOLEANO.toString())
                .concat("</span></div><div class=\"codigo2\">BANDERA = <span class=\"booleano\">")
                .concat(TPReservada.VERDADERO.toString())
                .concat("</span></div><div class=\"codigo1\"><span class=\"palabra\">")
                .concat(TPReservada.MIENTRAS.toString())
                .concat("</span> BANDERA <span class=\"palabra\">")
                .concat(TPReservada.ENTONCES.toString())
                .concat("</span></div><div class=\"codigo2\">&#09;INDEX = INDEX + <span class=\"numero\">1</span></div><div class=\"codigo1\">&#09;<span class=\"funcion\">")
                .concat(TPReservada.IMPRIME.toString())
                .concat("</span> INDEX</div><div class=\"codigo2\">&#09;<span class=\"palabra\">")
                .concat(TPReservada.SI.toString())
                .concat("</span> INDEX <span class=\"palabra\">")
                .concat(TPReservada.MAYORQUE.toString())
                .concat("</span> <span class=\"numero\">10</span> <span class=\"palabra\">")
                .concat(TPReservada.ENTONCES.toString())
                .concat("</span> </div><div class=\"codigo1\">&#09;&#09;BANDERA = <span class=\"booleano\">")
                .concat(TPReservada.FALSO.toString())
                .concat("</span></div><div class=\"codigo2\">&#09;<span class=\"palabra\">")
                .concat(TPReservada.TSI.toString())
                .concat("</span></div><div class=\"codigo1\"><span class=\"palabra\">")
                .concat(TPReservada.TMIENTRAS.toString())
                .concat("</span></div><div class=\"codigo2\"><span class=\"funcion\">")
                .concat(TPReservada.IMPRIME.toString())
                .concat("</span> <span class=\"cadena\">\"Sale del ciclo\"</span></div></div><br/>"),
                "Ciclos", interfaz);
    }
}
